<#
.SYNOPSIS
    Packages the current Raphael version into a Thunderstore-uploadable zip.

.DESCRIPTION
    Runs from the Raphael repo root. Steps:
      1. Reads version from Raphael/Raphael.csproj.
      2. Runs preflight in Release mode (fails fast if any check fails).
      3. dotnet build Release (no DeployToClient — we only need bin output).
      4. Stages dist/Raphael-{version}/ with the exact file set
         Thunderstore expects:
           - Raphael.dll  (the plugin)
           - manifest.json      (generated by Manifest.props)
           - icon.png           (256x256, validated by preflight)
           - README.md, LICENSE.txt, CHANGELOG.md
      5. Creates dist/Raphael-{version}.zip — drag-and-drop ready for
         https://thunderstore.io/c/v-rising/create/

    The zip layout is FILES AT ROOT (no enclosing folder inside the zip),
    matching Thunderstore's required structure.

    -SkipPreflight   skips step 2; useful if you already ran it.
    -SkipBuild       skips step 3; assumes bin/Release/net6.0/ is current.
    -Force           overwrites an existing dist/Raphael-{version}.zip.

.EXAMPLE
    .\tools\package-release.ps1
    .\tools\package-release.ps1 -Force
#>

[CmdletBinding()]
param(
    [switch]$SkipPreflight,
    [switch]$SkipBuild,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

# 1. Read version ----------------------------------------------------------
$csproj = Join-Path $repoRoot 'Raphael\Raphael.csproj'
if (-not (Test-Path $csproj)) { throw "Missing $csproj" }
$verMatch = [regex]::Match((Get-Content $csproj -Raw), '<Version>\s*([0-9]+\.[0-9]+\.[0-9]+)\s*</Version>')
if (-not $verMatch.Success) { throw "Could not parse <Version> from $csproj" }
$version = $verMatch.Groups[1].Value
Write-Host "Packaging Raphael v$version" -ForegroundColor Cyan

$stageDir = Join-Path $repoRoot "dist\Raphael-$version"
$zipPath  = Join-Path $repoRoot "dist\Raphael-$version.zip"

if ((Test-Path $zipPath) -and -not $Force) {
    throw "$zipPath already exists. Re-run with -Force to overwrite."
}

# 2. Preflight -------------------------------------------------------------
if (-not $SkipPreflight) {
    Write-Host "Running preflight (Release mode)..." -ForegroundColor Cyan
    & (Join-Path $PSScriptRoot 'preflight.ps1') -Mode Release
    if ($LASTEXITCODE -ne 0) {
        throw "Preflight failed. Re-run with -SkipPreflight only if you've reviewed the failures."
    }
}

# 3. Build -----------------------------------------------------------------
$dll      = Join-Path $repoRoot 'Raphael\bin\Release\net6.0\Raphael.dll'
$manifest = Join-Path $repoRoot 'Raphael\obj\Release\net6.0\manifest.json'
if (-not $SkipBuild) {
    Write-Host "dotnet build Release..." -ForegroundColor Cyan
    & dotnet build (Join-Path $repoRoot 'Raphael\Raphael.csproj') -c Release --nologo | Out-Host
    if ($LASTEXITCODE -ne 0) { throw "dotnet build failed." }
}
if (-not (Test-Path $dll))      { throw "Built DLL missing: $dll. Re-run without -SkipBuild." }
if (-not (Test-Path $manifest)) { throw "Generated manifest missing: $manifest. Re-run without -SkipBuild." }

# 4. Stage -----------------------------------------------------------------
if (Test-Path $stageDir) { Remove-Item -Recurse -Force $stageDir }
New-Item -ItemType Directory -Path $stageDir | Out-Null

$icon       = Join-Path $repoRoot 'Raphael\icon.png'
$readme     = Join-Path $repoRoot 'README.md'
$license    = Join-Path $repoRoot 'LICENSE.txt'
$changelog  = Join-Path $repoRoot 'CHANGELOG.md'

# The Thunderstore page shows the bundled CHANGELOG.md, so we bundle the
# concise, reader-friendly CHANGELOG.thunderstore.md there (milestone highlights
# with collapsed deep history). The full per-patch CHANGELOG.md stays at the repo
# root as the canonical archive on GitHub — both the README and the abbreviated
# changelog's header link to it. (Thunderstore also rejects a CHANGELOG over
# 100,000 chars, which the abbreviated one comfortably avoids.)
$thunderstoreChangelog = Join-Path $repoRoot 'CHANGELOG.thunderstore.md'
$changelogForZip = if (Test-Path $thunderstoreChangelog) {
    Write-Host ("Bundling CHANGELOG.thunderstore.md ({0:N1} KB) for the store page." -f ((Get-Item $thunderstoreChangelog).Length/1KB)) -ForegroundColor DarkGray
    $thunderstoreChangelog
} else {
    Write-Host ("CHANGELOG.thunderstore.md missing — bundling full CHANGELOG.md ({0:N1} KB)." -f ((Get-Item $changelog).Length/1KB)) -ForegroundColor Yellow
    $changelog
}

Copy-Item $dll              (Join-Path $stageDir 'Raphael.dll')
Copy-Item $manifest         (Join-Path $stageDir 'manifest.json')
Copy-Item $icon             (Join-Path $stageDir 'icon.png')
Copy-Item $readme           (Join-Path $stageDir 'README.md')
Copy-Item $license          (Join-Path $stageDir 'LICENSE.txt')
Copy-Item $changelogForZip  (Join-Path $stageDir 'CHANGELOG.md')

# 5. Zip -------------------------------------------------------------------
if (Test-Path $zipPath) { Remove-Item -Force $zipPath }

# Files-at-root: zip the contents of $stageDir, not the folder itself.
Compress-Archive -Path (Join-Path $stageDir '*') -DestinationPath $zipPath -Force

# Verify --------------------------------------------------------------------
$info = Get-Item $zipPath
Write-Host ''
Write-Host "Packaged: $zipPath" -ForegroundColor Green
Write-Host "  Size: $([math]::Round($info.Length / 1024, 1)) KB"
Write-Host "  Contents:"
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
foreach ($entry in ($archive.Entries | Sort-Object FullName)) {
    Write-Host ("    {0,-24} {1,8} bytes" -f $entry.FullName, $entry.Length)
}
$archive.Dispose()

Write-Host ''
Write-Host "Upload at: https://thunderstore.io/c/v-rising/create/" -ForegroundColor Cyan
